import json

urls = """
https://www.shwapno.com/food
https://www.shwapno.com/fruits-and-vegetables
https://www.shwapno.com/fresh-fruits
https://www.shwapno.com/fresh-vegetables
https://www.shwapno.com/dry-fruits
https://www.shwapno.com/dry-vegetables
https://www.shwapno.com/meat-and-fish
https://www.shwapno.com/fish
https://www.shwapno.com/fresh-water-fish
https://www.shwapno.com/sea-fish
https://www.shwapno.com/meat
https://www.shwapno.com/beef
https://www.shwapno.com/chicken
https://www.shwapno.com/mutton
https://www.shwapno.com/other-birds
https://www.shwapno.com/eggs
https://www.shwapno.com/baking-needs
https://www.shwapno.com/baking-ingredients
https://www.shwapno.com/flours
https://www.shwapno.com/colours-and-flavors
https://www.shwapno.com/beverages
https://www.shwapno.com/tea
https://www.shwapno.com/Black-Tea-2
https://www.shwapno.com/Green-Tea-2
https://www.shwapno.com/Flavored-Tea
https://www.shwapno.com/Tea-Others
https://www.shwapno.com/coffee
https://www.shwapno.com/Instant-Coffee
https://www.shwapno.com/Coffee-Mate
https://www.shwapno.com/Coffee-Others
https://www.shwapno.com/juice
https://www.shwapno.com/soft-drinks
https://www.shwapno.com/energy-and-malted-drinks
https://www.shwapno.com/syrups-and-powder-drinks
https://www.shwapno.com/drinking-water
https://www.shwapno.com/snacks
https://www.shwapno.com/Noodles
https://www.shwapno.com/Pasta
https://www.shwapno.com/Macaroni
https://www.shwapno.com/soup
https://www.shwapno.com/cakes
https://www.shwapno.com/biscuits
https://www.shwapno.com/Energy-Biscuit
https://www.shwapno.com/Milk-Biscuits
https://www.shwapno.com/Cream-Sandwich-Biscuits
https://www.shwapno.com/Toast-Biscuit
https://www.shwapno.com/Salted
https://www.shwapno.com/Sugar-Free-Biscuits
https://www.shwapno.com/Dry-Cake
https://www.shwapno.com/Biscuits-Others
https://www.shwapno.com/local-snacks
https://www.shwapno.com/popcorn-and-nuts
https://www.shwapno.com/chips-and-pretzels
https://www.shwapno.com/dried-fruits
https://www.shwapno.com/mayonnaise
https://www.shwapno.com/shemai-and-suji
https://www.shwapno.com/Frozen
https://www.shwapno.com/Paratha
https://www.shwapno.com/Singara
https://www.shwapno.com/Samosa
https://www.shwapno.com/Nuggets
https://www.shwapno.com/Sausage
https://www.shwapno.com/French-Fries
https://www.shwapno.com/Frozen-Snacks-Others
https://www.shwapno.com/canned-food
https://www.shwapno.com/Canned-Vegetables
https://www.shwapno.com/Canned-Fish
https://www.shwapno.com/Canned-Fruits
https://www.shwapno.com/Canned-Meat-2
https://www.shwapno.com/ice-cream
https://www.shwapno.com/candy-chocolate
https://www.shwapno.com/dairy
https://www.shwapno.com/ghee
https://www.shwapno.com/butter
https://www.shwapno.com/Cheese
https://www.shwapno.com/condensed-milk-and-cream
https://www.shwapno.com/liquid-and-uht-milk
https://www.shwapno.com/Low-Fat-Milk-2
https://www.shwapno.com/Milk-Others
https://www.shwapno.com/powder-milk
https://www.shwapno.com/Full-Cream-Milk
https://www.shwapno.com/Diabetic-Milk
https://www.shwapno.com/Low-Fat-Milk
https://www.shwapno.com/Non-Fat-Milk
https://www.shwapno.com/Powder-Milk-Others
https://www.shwapno.com/Yogurt
https://www.shwapno.com/Laban
https://www.shwapno.com/Lacchi
https://www.shwapno.com/breakfast
https://www.shwapno.com/breads
https://www.shwapno.com/jam-and-jelly
https://www.shwapno.com/dips-and-spreads
https://www.shwapno.com/honey
https://www.shwapno.com/cereals
https://www.shwapno.com/sauces-and-pickles
https://www.shwapno.com/pickle-and-condiments
https://www.shwapno.com/dipping-sauce
https://www.shwapno.com/cooking-sauce
https://www.shwapno.com/cooking
https://www.shwapno.com/rice
https://www.shwapno.com/loose-rice
https://www.shwapno.com/packed-rice
https://www.shwapno.com/daal-or-lentil
https://www.shwapno.com/loose-daal
https://www.shwapno.com/packed-daal
https://www.shwapno.com/oil
https://www.shwapno.com/soybean-oil
https://www.shwapno.com/rice-bran-oil
https://www.shwapno.com/sunflower-oil
https://www.shwapno.com/olive-oil
https://www.shwapno.com/mustard-oil
https://www.shwapno.com/flavored-oil
https://www.shwapno.com/spices
https://www.shwapno.com/Regular-Spice
https://www.shwapno.com/Mixed-Spice
https://www.shwapno.com/Wholespice
https://www.shwapno.com/salt-and-sugar
https://www.shwapno.com/salt
https://www.shwapno.com/sugar
https://www.shwapno.com/baby-food-and-care
https://www.shwapno.com/baby-food
https://www.shwapno.com/baby-wipes
https://www.shwapno.com/baby-bath-and-skincare
https://www.shwapno.com/baby-oral-care
https://www.shwapno.com/baby-accessories
https://www.shwapno.com/Diaper
https://www.shwapno.com/baby-diapers
https://www.shwapno.com/home-cleaning
https://www.shwapno.com/dish-cleaner
https://www.shwapno.com/laundry
https://www.shwapno.com/air-fresheners
https://www.shwapno.com/floor-glass-and-wood-cleaners
https://www.shwapno.com/toilet-cleaners
https://www.shwapno.com/pest-control
https://www.shwapno.com/trash-supplies
https://www.shwapno.com/pet-care
https://www.shwapno.com/cat-food
https://www.shwapno.com/beauty-and-health
https://www.shwapno.com/personal-care
https://www.shwapno.com/bath-and-body
https://www.shwapno.com/skincare
https://www.shwapno.com/talcum-powder
https://www.shwapno.com/Shampoo
https://www.shwapno.com/Conditioners
https://www.shwapno.com/cream-and-lotion
https://www.shwapno.com/cosmetics
https://www.shwapno.com/hair-care
https://www.shwapno.com/shaving-and-facial-care
https://www.shwapno.com/feminine-care
https://www.shwapno.com/oral-care
https://www.shwapno.com/deodorant
https://www.shwapno.com/tissue-and-wipes
https://www.shwapno.com/personal-grooming
https://www.shwapno.com/handwash-and-handrub
https://www.shwapno.com/health-care
https://www.shwapno.com/herbal-and-digestive-aids
https://www.shwapno.com/first-aid-and-antiseptics
https://www.shwapno.com/diabetic-sugar
https://www.shwapno.com/Medical-Devices
https://www.shwapno.com/fashion-and-lifestyle
https://www.shwapno.com/kurtis-tunics-and-tops
https://www.shwapno.com/skirts-and-palazzos
https://www.shwapno.com/lungi
https://www.shwapno.com/home-and-kitchen
https://www.shwapno.com/Home-Appliance-2
https://www.shwapno.com/Fan
https://www.shwapno.com/Iron
https://www.shwapno.com/kitchen-accessories
https://www.shwapno.com/kitchen-appliances
https://www.shwapno.com/flask-pots-and-bottles
https://www.shwapno.com/cookware
https://www.shwapno.com/crockeries
https://www.shwapno.com/spoons-forks-and-others
https://www.shwapno.com/living-items
https://www.shwapno.com/towels
https://www.shwapno.com/bedding
https://www.shwapno.com/pillow-and-cushion
https://www.shwapno.com/blanket-and-comforter
https://www.shwapno.com/bed-room-essentials
https://www.shwapno.com/lights-and-electrical
https://www.shwapno.com/tools-and-hardware
https://www.shwapno.com/office-products
https://www.shwapno.com/batteries
https://www.shwapno.com/writing-and-drawing
https://www.shwapno.com/colours
https://www.shwapno.com/toys-and-sports
https://www.shwapno.com/toys-items
https://www.shwapno.com/Gadget
https://www.shwapno.com/deals
https://www.shwapno.com/deals-on-unilever
https://www.shwapno.com/buy-save-more-2
"""

categories = []
for line in urls.splitlines():
    url = line.strip()
    if url:
        name = url.split('/')[-1].replace('-', ' ').title()
        categories.append({
            "name": name,
            "url": url,
            "enabled": True
        })

with open('categories.json', 'w') as f:
    json.dump(categories, f, indent=2)

print(f"Generated {len(categories)} categories.")
